### ISSUE TITLE
[数独入门解法逐步优化与分析] 利用二進制狀態壓縮

### ISSUE THREAD

**Issue by aben20807** [siahuat0727/siahuat0727.github.io#1]
因為沒有留言區，所以.... OuO
我在[浅谈信息学竞赛中的“0”和“1”——二进制思想在信息学竞赛中的应用](https://github.com/oeddyo/algorithm/blob/master/resources/%E7%89%9B%E4%BA%BA%E8%B0%88ACM%E7%BB%8F%E9%AA%8C(%E5%8C%85%E6%8B%AC%E5%9B%BD%E5%AE%B6%E9%9B%86%E8%AE%AD%E9%98%9F%E8%AE%BA%E6%96%87)/%E5%9B%BD%E5%AE%B6%E9%9B%86%E8%AE%AD%E9%98%9F%E8%AE%BA%E6%96%87/%E5%9B%BD%E5%AE%B6%E9%9B%86%E8%AE%AD%E9%98%9F2009%E8%AE%BA%E6%96%87%E9%9B%86/1.%E6%AD%A6%E6%A3%AE%E3%80%8A%E6%B5%85%E8%B0%88%E4%BF%A1%E6%81%AF%E5%AD%A6%E7%AB%9E%E8%B5%9B%E4%B8%AD%E7%9A%84%E2%80%9C0%E2%80%9D%E5%92%8C%E2%80%9C1%E2%80%9D%E3%80%8B/%E6%B5%85%E8%B0%88%E4%BF%A1%E6%81%AF%E5%AD%A6%E7%AB%9E%E8%B5%9B%E4%B8%AD%E7%9A%84%E2%80%9C0%E2%80%9D%E5%92%8C%E2%80%9C1%E2%80%9D.pdf)看到數獨也能用到二進位去壓縮狀態，實作好像在[算法实践——数独的基本解法](http://www.cnblogs.com/grenet/p/3138654.html)有，不過是用VB寫的。
我不知道會不會比較快，不過感覺你應該沒有用過所以就來發個 issue~

**Comment by siahuat0727** [comment]
嗨嗨～～
之後會嘗試做留言區xP
我之前有看到類似的想法
所以題目才會是 入門解法～
這篇也還沒寫完，
等寫完了有機會可以嘗試看看。
